MoveBase:
  controller_frequency: [10, 10]
  planner_patience: [3.0, 7.0]
  controller_patience: [10.0, 20.0]
  conservative_reset_dist: [2.0, 5.0]
  planner_frequency: [5.0, 5.0]
  oscillation_timeout: [10.0, 10.0]
  oscillation_distance: [0.1, 0.3]

DWAPlannerROS:
  acc_lim_theta: [3.2, 3.2]
  acc_lim_trans: [0.1, 0.1]
  acc_lim_x: [2.5, 2.5]
  acc_lim_y: [0.0, 0.0]
  angular_sim_granularity: [0.1, 0.1] 
  forward_point_distance: [0.325, 0.325]
  goal_distance_bias: [10.0, 40.0]
  max_scaling_factor: [0.1, 1]
  max_vel_theta: [2.75, 2.75]
  max_vel_trans: [0.22, 0.22]
  max_vel_x: [0.22, 0.22]
  max_vel_y: [0.0, 0.0]
  min_vel_theta: [1.37, 1.37]
  min_vel_trans: [0.11, 0.11]
  min_vel_x: [-0.5, 0.0]
  min_vel_y: [0.0, 0.0]
  occdist_scale: [0.01, 0.1]
  oscillation_reset_angle: [0.2, 0.2]
  oscillation_reset_dist: [0.05, 0.05]
  path_distance_bias: [10, 50]
  scaling_speed: [0.25, 0.25]
  sim_granularity: [0.025, 0.025]
  sim_time: [0.5, 5]
  stop_time_buffer: [0.2, 0.5]
  theta_stopped_vel: [0.1, 0.1]
  trans_stopped_vel: [0.1, 0.1]
  twirling_scale: [0.0, 0.0]
  vth_samples: [10, 50]
  vx_samples: [10, 50]
  vy_samples: [0, 0]
  xy_goal_tolerance: [0.01, 0.5]
  yaw_goal_tolerance: [0.01, 0.5]

costmap_common:
  publish_frequency: [5.0, 20.0]
  resolution: [0.01, 0.1] 
  transform_tolerance: [0.1, 5.0]
  update_frequency: [5.0, 20.0] 
    
costmap_common_inflation:
  cost_scaling_factor: [5.0, 50.0]
  inflation_radius: [0.1, 2.0]  
